### ISSUE TITLE
flash target issue.

### ISSUE THREAD

**Issue by colasianPotat** [dazKind/foo3d#2]
compiling any sample on ubuntu 10.04 (hxcpp works) compiles but doesn't seem to run in browser. using the provided html and using the swfs from http://foo3d.developium.net/ doesn't work as well. what am i doing wrong! does it require something special from a web server?

**Comment by dazKind** [comment]
In order to run the html+swf you need to serve it through a webserver. Otherwise flash will start with some weird sandboxing(since it's a file-url, and not a real one) and screw up.

I do this via 

```
cd foo3d/samples
python -m SimpleHTTPServer 2001
```

and open the url `http://localhost:2001/<sampledirname>/swf` in my browser.

Alternatively you can use the [nekotools webserver](http://blog.presidentbeef.com/neko_tutorial/tools.html) to serve the files
